#!/bin/bash

# This script make a symlink of your rails app to use it with Pow.
# As a requirement, you need Pow to be installed.

# Copyright (C) 2013  João Gabriel P. Bellon

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or 
# any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses.

# Check if pow is installed, if not, then installs it.

POW_ROOT="$HOME/Library/Application Support/Pow"
APP_ROOT="$1"
APP_NAME="$2"

if [ ! -d "$POW_ROOT" ]; then
	echo "Proceeding to Pow installation..."
	curl get.pow.cx | sh
else
	echo "Pow already installed!"
	
	# cd to Pow symlink
	echo "Going tp  ~/.pow"
	cd ~/.pow

	# Create the symlink for the app
	echo Creating the symlink for the app "$APP_NAME" located at "$APP_ROOT"
	ln -s "$APP_ROOT"$APP_NAME

	# Redirects to app location
	open http://test-app.dev/
fi
